# Generated by Django 3.2.3 on 2021-05-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='FreeToAdd'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='NewPaper', max_length=255),
        ),
    ]
