# Generated by Django 3.2.3 on 2021-05-28 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210528_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_author_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to='news.author'),
        ),
    ]
